export const FOLDER_SELECTED = 'FOLDER_SELECTED';
export const FOLDER_OPTIONS = 'FOLDER_OPTIONS';
export const NEW_FOLDER = 'NEW_FOLDER';
export const REMOVE_FOLDER = 'REMOVE_FOLDER';
export const FOLDER_TO_RENAME = 'FOLDER_TO_RENAME';
export const RENAME_FOLDER = 'RENAME_FOLDER';
